/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-16 01:40:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/../include/navigation.jsp", Long.valueOf(1565915646739L));
    _jspx_dependants.put("/views/../include/commonTags.jsp", Long.valueOf(1565916334527L));
    _jspx_dependants.put("/views/../include/footer.jsp", Long.valueOf(1565915749032L));
    _jspx_dependants.put("/views/../include/commonScript.jsp", Long.valueOf(1565917813815L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<title>아기어때</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScripts -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">아기어때</a>\r\n");
      out.write("    <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      Menu\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("      <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/\">마이페이지</a>\r\n");
      out.write("          \t\t\t\t<!-- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/xxx.jsp로 바로 넘겨도 되고, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/xxx.do로 넘겨도 됨 -->\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/\">아이페이지</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/\">제품추천</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/\">게시판</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/\">나눔</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t<!-- /Navigation -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t<!-- 개별 이용 division -->\r\n");
      out.write("\t<section class=\"bg-light page-section\" id=\"portfolio\"><!-- section1 -->\r\n");
      out.write("\t\t<div class=\"container\"><!-- container1 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"row\"><!-- row1 -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading text-uppercase\">페이지 타이틀</h2>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"section-subheading text-muted\">타이틀 소제목 or 설명</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- /row1 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\"><!-- row2 -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/01-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-1번</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Illustration</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/02-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-2번</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Graphic Design</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/03-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-3번</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Identity</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t    <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/04-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-4번(2줄 1번)</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Branding</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/05-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-5번(2줄 2번)</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Website Design</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio-hover-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/img/portfolio/06-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h4>row-6번(2줄 3번)</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Photography</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div><!-- /row2 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\"><!-- row3 -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\" style=\"border: 1px solid black\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading text-uppercase\">페이지 타이틀</h2>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"section-subheading text-muted\">타이틀 소제목 or 설명</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\" style=\"border: 1px solid black\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading text-uppercase\">페이지 타이틀</h2>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"section-subheading text-muted\">타이틀 소제목 or 설명</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- /row3 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- class명에있는 col-md는 가로를 의미 -->\r\n");
      out.write("\t\t\t<!-- row당 총 12칸이기 때문에 row3의 경우처럼 하위의 div가 \"col-md-6\"의 크기라면 row안에 2개밖에 안들어감-->\r\n");
      out.write("\t\t\t<!-- 템플릿에서는 col-md-4를 쓰고 있기 때문에 1개의 row안에 3개씩 들어감 -->\r\n");
      out.write("\t\t\t<!-- division 만들때 굳이 따로 width를 설정할 필요없이 container와 row로 크기를 쉽게 구성해서 쓸 수 있음 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><!-- /container1 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section><!-- /section1 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row align-items-center\">\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <span class=\"copyright\">Copyright &copy; BabyAttack</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <ul class=\"list-inline social-buttons\">\r\n");
      out.write("          <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <ul class=\"list-inline quicklinks\">\r\n");
      out.write("          <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"#\">Terms of Use</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Common Script -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JavaScript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Contact form JavaScript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for this template -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/js/agency.min.js\"></script>");
      out.write("\r\n");
      out.write("\t<!-- /Common Script -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
